/**
 * Tool definitions for FreeAgent API gap coverage.
 * Merged into the main catalog by register.ts.
 */

import type { ToolDefinition } from "./register.js";

import { updateContact, deleteContact } from "./contacts.js";
import { updateBill, deleteBill } from "./bills.js";
import { updateProject, deleteProject } from "./projects.js";
import { updateTask, deleteTask } from "./tasks.js";
import { deleteExpense, getMileageSettings } from "./expenses.js";
import { updatePriceListItem, deletePriceListItem } from "./price-list-items.js";
import { deleteTimeslip } from "./timeslips.js";
import { createCategory, updateCategory, deleteCategory } from "./categories.js";
import { updateInvoice, deleteInvoice, duplicateInvoice, sendInvoiceEmail, getInvoiceTimeline, directDebitInvoice } from "./invoices.js";
import { updateEstimate, deleteEstimate, duplicateEstimate, sendEstimateEmail } from "./estimates.js";
import { createBankAccount, updateBankAccount, deleteBankAccount, uploadBankStatement } from "./bank-accounts.js";
import { deleteBankTransactionExplanation } from "./bank-transactions.js";
import { listCreditNotes, getCreditNote, createCreditNote, updateCreditNote, deleteCreditNote, transitionCreditNote, sendCreditNoteEmail, listCreditNoteReconciliations, getCreditNoteReconciliation, createCreditNoteReconciliation, updateCreditNoteReconciliation, deleteCreditNoteReconciliation } from "./credit-notes.js";
import { listNotes, getNote, createNote, updateNote, deleteNote } from "./notes.js";
import { getAttachment, deleteAttachment } from "./attachments.js";
import { getProfitAndLoss, getBalanceSheet, getTrialBalance, getCashflow, listAccountingTransactions, getAccountingTransaction } from "./reports.js";
import { listJournalSets, getJournalSet, getOpeningBalances, createJournalSet, updateJournalSet, deleteJournalSet } from "./journals.js";
import { listCapitalAssets, getCapitalAsset, listCapitalAssetTypes, getCapitalAssetType, createCapitalAssetType, updateCapitalAssetType, deleteCapitalAssetType } from "./capital-assets.js";
import { listVatReturns, getVatReturn, transitionVatReturn, transitionVatReturnPayment, listCorporationTaxReturns, getCorporationTaxReturn, transitionCorporationTaxReturn, listFinalAccountsReports, getFinalAccountsReport, transitionFinalAccountsReport, listIncomeTaxReturns, getIncomeTaxReturn, transitionIncomeTaxReturn, transitionIncomeTaxReturnPayment } from "./tax-returns.js";
import { listPayrollPeriods, listPayrollPayslips, transitionPayrollPayment, listPayrollProfiles, getPayrollProfile } from "./payroll.js";
import { listProperties, getProperty, createProperty, updateProperty, deleteProperty, listStockItems, getStockItem, listHirePurchases, getHirePurchase } from "./properties-stock.js";
import { listBankFeeds, getBankFeed, listEmailAddresses, listAccountLocks, setAccountLock, deleteAccountLock, listCisBands, getCisSettings, updateCisSettings, listSalesTaxPeriods, getSalesTaxPeriod, createSalesTaxPeriod, updateSalesTaxPeriod, deleteSalesTaxPeriod, getCompanyBusinessCategories, getCompanyTaxTimeline, getUser, createUser, updateUser, deleteUser } from "./misc-company-api.js";
import {
  CreateBankAccountInputSchema,
  CreateCapitalAssetTypeInputSchema,
  CreateCategoryInputSchema,
  CreateCreditNoteInputSchema,
  CreateCreditNoteReconciliationInputSchema,
  CreateJournalSetInputSchema,
  CreateNoteInputSchema,
  CreatePropertyInputSchema,
  CreateSalesTaxPeriodInputSchema,
  CreateUserInputSchema,
  DeleteAccountLockInputSchema,
  DeleteAttachmentInputSchema,
  DeleteBankAccountInputSchema,
  DeleteBankTransactionExplanationInputSchema,
  DeleteBillInputSchema,
  DeleteCapitalAssetTypeInputSchema,
  DeleteCategoryInputSchema,
  DeleteContactInputSchema,
  DeleteCreditNoteInputSchema,
  DeleteCreditNoteReconciliationInputSchema,
  DeleteEstimateInputSchema,
  DeleteExpenseInputSchema,
  DeleteInvoiceInputSchema,
  DeleteJournalSetInputSchema,
  DeleteNoteInputSchema,
  DeletePriceListItemInputSchema,
  DeleteProjectInputSchema,
  DeletePropertyInputSchema,
  DeleteSalesTaxPeriodInputSchema,
  DeleteTaskInputSchema,
  DeleteTimeslipInputSchema,
  DeleteUserInputSchema,
  DirectDebitInvoiceInputSchema,
  DuplicateEstimateInputSchema,
  DuplicateInvoiceInputSchema,
  GetAccountingTransactionInputSchema,
  GetAttachmentInputSchema,
  GetBalanceSheetInputSchema,
  GetBankFeedInputSchema,
  GetCapitalAssetInputSchema,
  GetCapitalAssetTypeInputSchema,
  GetCashflowInputSchema,
  GetCisSettingsInputSchema,
  GetCompanyBusinessTypesInputSchema,
  GetCompanyTaxTimelineInputSchema,
  GetCorporationTaxReturnInputSchema,
  GetCreditNoteInputSchema,
  GetCreditNoteReconciliationInputSchema,
  GetFinalAccountsReportInputSchema,
  GetHirePurchaseInputSchema,
  GetIncomeTaxReturnInputSchema,
  GetInvoiceTimelineInputSchema,
  GetJournalSetInputSchema,
  GetMileageSettingsInputSchema,
  GetNoteInputSchema,
  GetOpeningBalancesInputSchema,
  GetPayrollProfileInputSchema,
  GetProfitAndLossInputSchema,
  GetPropertyInputSchema,
  GetSalesTaxPeriodInputSchema,
  GetStockItemInputSchema,
  GetTrialBalanceInputSchema,
  GetUserInputSchema,
  GetVatReturnInputSchema,
  ListAccountLocksInputSchema,
  ListAccountingTransactionsInputSchema,
  ListBankFeedsInputSchema,
  ListCapitalAssetTypesInputSchema,
  ListCapitalAssetsInputSchema,
  ListCisBandsInputSchema,
  ListCorporationTaxReturnsInputSchema,
  ListCreditNoteReconciliationsInputSchema,
  ListCreditNotesInputSchema,
  ListEmailAddressesInputSchema,
  ListFinalAccountsReportsInputSchema,
  ListHirePurchasesInputSchema,
  ListIncomeTaxReturnsInputSchema,
  ListJournalSetsInputSchema,
  ListNotesInputSchema,
  ListPayrollPayslipsInputSchema,
  ListPayrollPeriodsInputSchema,
  ListPayrollProfilesInputSchema,
  ListPropertiesInputSchema,
  ListSalesTaxPeriodsInputSchema,
  ListStockItemsInputSchema,
  ListVatReturnsInputSchema,
  SendCreditNoteEmailInputSchema,
  SendEstimateEmailInputSchema,
  SendInvoiceEmailInputSchema,
  SetAccountLockInputSchema,
  TransitionCorporationTaxReturnInputSchema,
  TransitionCreditNoteInputSchema,
  TransitionFinalAccountsReportInputSchema,
  TransitionIncomeTaxReturnInputSchema,
  TransitionIncomeTaxReturnPaymentInputSchema,
  TransitionPayrollPaymentInputSchema,
  TransitionVatReturnInputSchema,
  TransitionVatReturnPaymentInputSchema,
  UpdateBankAccountInputSchema,
  UpdateBillInputSchema,
  UpdateCapitalAssetTypeInputSchema,
  UpdateCategoryInputSchema,
  UpdateCisSettingsInputSchema,
  UpdateContactInputSchema,
  UpdateCreditNoteInputSchema,
  UpdateCreditNoteReconciliationInputSchema,
  UpdateEstimateInputSchema,
  UpdateInvoiceInputSchema,
  UpdateJournalSetInputSchema,
  UpdateNoteInputSchema,
  UpdatePriceListItemInputSchema,
  UpdateProjectInputSchema,
  UpdatePropertyInputSchema,
  UpdateSalesTaxPeriodInputSchema,
  UpdateTaskInputSchema,
  UpdateUserInputSchema,
  UploadBankStatementInputSchema,
} from "../schemas/index.js";

export const gapToolDefinitions: ToolDefinition[] = [
  {
    name: "freeagent_update_contact",
    title: "FreeAgent Update Contact",
    description: "Update an existing FreeAgent contact. Only provide fields to change.",
    inputSchema: UpdateContactInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateContact,
  },
  {
    name: "freeagent_delete_contact",
    title: "FreeAgent Delete Contact",
    description: "Delete a FreeAgent contact by ID or URL.",
    inputSchema: DeleteContactInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteContact,
  },
  {
    name: "freeagent_update_bill",
    title: "FreeAgent Update Bill",
    description: "Update an existing supplier bill.",
    inputSchema: UpdateBillInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateBill,
  },
  {
    name: "freeagent_delete_bill",
    title: "FreeAgent Delete Bill",
    description: "Delete a supplier bill.",
    inputSchema: DeleteBillInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteBill,
  },
  {
    name: "freeagent_update_project",
    title: "FreeAgent Update Project",
    description: "Update an existing project.",
    inputSchema: UpdateProjectInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateProject,
  },
  {
    name: "freeagent_delete_project",
    title: "FreeAgent Delete Project",
    description: "Delete a project.",
    inputSchema: DeleteProjectInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteProject,
  },
  {
    name: "freeagent_update_task",
    title: "FreeAgent Update Task",
    description: "Update an existing task.",
    inputSchema: UpdateTaskInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateTask,
  },
  {
    name: "freeagent_delete_task",
    title: "FreeAgent Delete Task",
    description: "Delete a task.",
    inputSchema: DeleteTaskInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteTask,
  },
  {
    name: "freeagent_delete_expense",
    title: "FreeAgent Delete Expense",
    description: "Delete an expense.",
    inputSchema: DeleteExpenseInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteExpense,
  },
  {
    name: "freeagent_get_mileage_settings",
    title: "FreeAgent Get Mileage Settings",
    description: "Get company mileage reimbursement settings.",
    inputSchema: GetMileageSettingsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getMileageSettings,
  },
  {
    name: "freeagent_update_price_list_item",
    title: "FreeAgent Update Price List Item",
    description: "Update a price list catalog item.",
    inputSchema: UpdatePriceListItemInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updatePriceListItem,
  },
  {
    name: "freeagent_delete_price_list_item",
    title: "FreeAgent Delete Price List Item",
    description: "Delete a price list catalog item.",
    inputSchema: DeletePriceListItemInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deletePriceListItem,
  },
  {
    name: "freeagent_delete_timeslip",
    title: "FreeAgent Delete Timeslip",
    description: "Delete a timeslip. Timers are intentionally not exposed.",
    inputSchema: DeleteTimeslipInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteTimeslip,
  },
  {
    name: "freeagent_create_category",
    title: "FreeAgent Create Category",
    description: "Create a custom accounting category.",
    inputSchema: CreateCategoryInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createCategory,
  },
  {
    name: "freeagent_update_category",
    title: "FreeAgent Update Category",
    description: "Update a custom category by nominal code.",
    inputSchema: UpdateCategoryInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateCategory,
  },
  {
    name: "freeagent_delete_category",
    title: "FreeAgent Delete Category",
    description: "Delete a custom category by nominal code.",
    inputSchema: DeleteCategoryInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteCategory,
  },
  {
    name: "freeagent_update_invoice",
    title: "FreeAgent Update Invoice",
    description: "Update a draft/editable invoice.",
    inputSchema: UpdateInvoiceInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateInvoice,
  },
  {
    name: "freeagent_delete_invoice",
    title: "FreeAgent Delete Invoice",
    description: "Delete an invoice.",
    inputSchema: DeleteInvoiceInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteInvoice,
  },
  {
    name: "freeagent_duplicate_invoice",
    title: "FreeAgent Duplicate Invoice",
    description: "Duplicate an invoice into a new draft.",
    inputSchema: DuplicateInvoiceInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: duplicateInvoice,
  },
  {
    name: "freeagent_send_invoice_email",
    title: "FreeAgent Send Invoice Email",
    description: "Email an invoice to a contact (uses verified sender addresses).",
    inputSchema: SendInvoiceEmailInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: sendInvoiceEmail,
  },
  {
    name: "freeagent_get_invoice_timeline",
    title: "FreeAgent Get Invoice Timeline",
    description: "Get the company invoice timeline overview.",
    inputSchema: GetInvoiceTimelineInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getInvoiceTimeline,
  },
  {
    name: "freeagent_direct_debit_invoice",
    title: "FreeAgent Direct Debit Invoice",
    description: "Collect payment for an invoice via GoCardless Direct Debit.",
    inputSchema: DirectDebitInvoiceInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: directDebitInvoice,
  },
  {
    name: "freeagent_update_estimate",
    title: "FreeAgent Update Estimate",
    description: "Update an estimate.",
    inputSchema: UpdateEstimateInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateEstimate,
  },
  {
    name: "freeagent_delete_estimate",
    title: "FreeAgent Delete Estimate",
    description: "Delete an estimate.",
    inputSchema: DeleteEstimateInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteEstimate,
  },
  {
    name: "freeagent_duplicate_estimate",
    title: "FreeAgent Duplicate Estimate",
    description: "Duplicate an estimate into a new draft.",
    inputSchema: DuplicateEstimateInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: duplicateEstimate,
  },
  {
    name: "freeagent_send_estimate_email",
    title: "FreeAgent Send Estimate Email",
    description: "Email an estimate to a contact.",
    inputSchema: SendEstimateEmailInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: sendEstimateEmail,
  },
  {
    name: "freeagent_create_bank_account",
    title: "FreeAgent Create Bank Account",
    description: "Create a bank account.",
    inputSchema: CreateBankAccountInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createBankAccount,
  },
  {
    name: "freeagent_update_bank_account",
    title: "FreeAgent Update Bank Account",
    description: "Update a bank account.",
    inputSchema: UpdateBankAccountInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateBankAccount,
  },
  {
    name: "freeagent_delete_bank_account",
    title: "FreeAgent Delete Bank Account",
    description: "Delete a bank account.",
    inputSchema: DeleteBankAccountInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteBankAccount,
  },
  {
    name: "freeagent_upload_bank_statement",
    title: "FreeAgent Upload Bank Statement",
    description: "Upload bank statement lines as JSON (not a binary file).",
    inputSchema: UploadBankStatementInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: uploadBankStatement,
  },
  {
    name: "freeagent_delete_bank_transaction_explanation",
    title: "FreeAgent Delete Bank Transaction Explanation",
    description: "Delete a bank transaction explanation.",
    inputSchema: DeleteBankTransactionExplanationInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteBankTransactionExplanation,
  },
  {
    name: "freeagent_list_credit_notes",
    title: "FreeAgent List Credit Notes",
    description: "List credit notes with optional filters.",
    inputSchema: ListCreditNotesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listCreditNotes,
  },
  {
    name: "freeagent_get_credit_note",
    title: "FreeAgent Get Credit Note",
    description: "Get a credit note by ID.",
    inputSchema: GetCreditNoteInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCreditNote,
  },
  {
    name: "freeagent_create_credit_note",
    title: "FreeAgent Create Credit Note",
    description: "Create a draft credit note.",
    inputSchema: CreateCreditNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createCreditNote,
  },
  {
    name: "freeagent_update_credit_note",
    title: "FreeAgent Update Credit Note",
    description: "Update a credit note.",
    inputSchema: UpdateCreditNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateCreditNote,
  },
  {
    name: "freeagent_delete_credit_note",
    title: "FreeAgent Delete Credit Note",
    description: "Delete a credit note.",
    inputSchema: DeleteCreditNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteCreditNote,
  },
  {
    name: "freeagent_transition_credit_note",
    title: "FreeAgent Transition Credit Note",
    description: "Mark a credit note sent/draft/cancelled.",
    inputSchema: TransitionCreditNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionCreditNote,
  },
  {
    name: "freeagent_send_credit_note_email",
    title: "FreeAgent Send Credit Note Email",
    description: "Email a credit note.",
    inputSchema: SendCreditNoteEmailInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: sendCreditNoteEmail,
  },
  {
    name: "freeagent_list_credit_note_reconciliations",
    title: "FreeAgent List Credit Note Reconciliations",
    description: "List credit note reconciliations against invoices.",
    inputSchema: ListCreditNoteReconciliationsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listCreditNoteReconciliations,
  },
  {
    name: "freeagent_get_credit_note_reconciliation",
    title: "FreeAgent Get Credit Note Reconciliation",
    description: "Get a credit note reconciliation.",
    inputSchema: GetCreditNoteReconciliationInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCreditNoteReconciliation,
  },
  {
    name: "freeagent_create_credit_note_reconciliation",
    title: "FreeAgent Create Credit Note Reconciliation",
    description: "Apply a credit note to an invoice.",
    inputSchema: CreateCreditNoteReconciliationInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createCreditNoteReconciliation,
  },
  {
    name: "freeagent_update_credit_note_reconciliation",
    title: "FreeAgent Update Credit Note Reconciliation",
    description: "Update a credit note reconciliation.",
    inputSchema: UpdateCreditNoteReconciliationInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateCreditNoteReconciliation,
  },
  {
    name: "freeagent_delete_credit_note_reconciliation",
    title: "FreeAgent Delete Credit Note Reconciliation",
    description: "Delete a credit note reconciliation.",
    inputSchema: DeleteCreditNoteReconciliationInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteCreditNoteReconciliation,
  },
  {
    name: "freeagent_list_notes",
    title: "FreeAgent List Notes",
    description: "List notes for a contact or project.",
    inputSchema: ListNotesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listNotes,
  },
  {
    name: "freeagent_get_note",
    title: "FreeAgent Get Note",
    description: "Get a note by ID.",
    inputSchema: GetNoteInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getNote,
  },
  {
    name: "freeagent_create_note",
    title: "FreeAgent Create Note",
    description: "Create a note on a contact or project.",
    inputSchema: CreateNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createNote,
  },
  {
    name: "freeagent_update_note",
    title: "FreeAgent Update Note",
    description: "Update note text.",
    inputSchema: UpdateNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateNote,
  },
  {
    name: "freeagent_delete_note",
    title: "FreeAgent Delete Note",
    description: "Delete a note.",
    inputSchema: DeleteNoteInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteNote,
  },
  {
    name: "freeagent_get_attachment",
    title: "FreeAgent Get Attachment",
    description: "Get attachment metadata (download URL; bytes not inlined).",
    inputSchema: GetAttachmentInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getAttachment,
  },
  {
    name: "freeagent_delete_attachment",
    title: "FreeAgent Delete Attachment",
    description: "Delete an attachment.",
    inputSchema: DeleteAttachmentInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteAttachment,
  },
  {
    name: "freeagent_get_profit_and_loss",
    title: "FreeAgent Get Profit And Loss",
    description: "Get profit & loss summary for a date range.",
    inputSchema: GetProfitAndLossInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getProfitAndLoss,
  },
  {
    name: "freeagent_get_balance_sheet",
    title: "FreeAgent Get Balance Sheet",
    description: "Get balance sheet as at a date.",
    inputSchema: GetBalanceSheetInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getBalanceSheet,
  },
  {
    name: "freeagent_get_trial_balance",
    title: "FreeAgent Get Trial Balance",
    description: "Get trial balance summary (or opening balances).",
    inputSchema: GetTrialBalanceInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getTrialBalance,
  },
  {
    name: "freeagent_get_cashflow",
    title: "FreeAgent Get Cashflow",
    description: "Get cashflow for a date range.",
    inputSchema: GetCashflowInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCashflow,
  },
  {
    name: "freeagent_list_accounting_transactions",
    title: "FreeAgent List Accounting Transactions",
    description: "List accounting ledger transactions.",
    inputSchema: ListAccountingTransactionsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listAccountingTransactions,
  },
  {
    name: "freeagent_get_accounting_transaction",
    title: "FreeAgent Get Accounting Transaction",
    description: "Get an accounting transaction.",
    inputSchema: GetAccountingTransactionInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getAccountingTransaction,
  },
  {
    name: "freeagent_list_journal_sets",
    title: "FreeAgent List Journal Sets",
    description: "List journal sets.",
    inputSchema: ListJournalSetsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listJournalSets,
  },
  {
    name: "freeagent_get_journal_set",
    title: "FreeAgent Get Journal Set",
    description: "Get a journal set.",
    inputSchema: GetJournalSetInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getJournalSet,
  },
  {
    name: "freeagent_get_opening_balances",
    title: "FreeAgent Get Opening Balances",
    description: "Get opening balances journal set.",
    inputSchema: GetOpeningBalancesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getOpeningBalances,
  },
  {
    name: "freeagent_create_journal_set",
    title: "FreeAgent Create Journal Set",
    description: "Create a balanced journal set.",
    inputSchema: CreateJournalSetInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createJournalSet,
  },
  {
    name: "freeagent_update_journal_set",
    title: "FreeAgent Update Journal Set",
    description: "Update a journal set.",
    inputSchema: UpdateJournalSetInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateJournalSet,
  },
  {
    name: "freeagent_delete_journal_set",
    title: "FreeAgent Delete Journal Set",
    description: "Delete a journal set.",
    inputSchema: DeleteJournalSetInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteJournalSet,
  },
  {
    name: "freeagent_list_capital_assets",
    title: "FreeAgent List Capital Assets",
    description: "List capital assets.",
    inputSchema: ListCapitalAssetsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listCapitalAssets,
  },
  {
    name: "freeagent_get_capital_asset",
    title: "FreeAgent Get Capital Asset",
    description: "Get a capital asset.",
    inputSchema: GetCapitalAssetInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCapitalAsset,
  },
  {
    name: "freeagent_list_capital_asset_types",
    title: "FreeAgent List Capital Asset Types",
    description: "List capital asset types.",
    inputSchema: ListCapitalAssetTypesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listCapitalAssetTypes,
  },
  {
    name: "freeagent_get_capital_asset_type",
    title: "FreeAgent Get Capital Asset Type",
    description: "Get a capital asset type.",
    inputSchema: GetCapitalAssetTypeInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCapitalAssetType,
  },
  {
    name: "freeagent_create_capital_asset_type",
    title: "FreeAgent Create Capital Asset Type",
    description: "Create a capital asset type.",
    inputSchema: CreateCapitalAssetTypeInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createCapitalAssetType,
  },
  {
    name: "freeagent_update_capital_asset_type",
    title: "FreeAgent Update Capital Asset Type",
    description: "Update a capital asset type.",
    inputSchema: UpdateCapitalAssetTypeInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateCapitalAssetType,
  },
  {
    name: "freeagent_delete_capital_asset_type",
    title: "FreeAgent Delete Capital Asset Type",
    description: "Delete a capital asset type.",
    inputSchema: DeleteCapitalAssetTypeInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteCapitalAssetType,
  },
  {
    name: "freeagent_list_vat_returns",
    title: "FreeAgent List VAT Returns",
    description: "List VAT returns.",
    inputSchema: ListVatReturnsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listVatReturns,
  },
  {
    name: "freeagent_get_vat_return",
    title: "FreeAgent Get VAT Return",
    description: "Get a VAT return by period end date.",
    inputSchema: GetVatReturnInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getVatReturn,
  },
  {
    name: "freeagent_transition_vat_return",
    title: "FreeAgent Transition VAT Return",
    description: "Mark a VAT return filed/unfiled.",
    inputSchema: TransitionVatReturnInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionVatReturn,
  },
  {
    name: "freeagent_transition_vat_return_payment",
    title: "FreeAgent Transition VAT Return Payment",
    description: "Mark a VAT return payment paid/unpaid.",
    inputSchema: TransitionVatReturnPaymentInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionVatReturnPayment,
  },
  {
    name: "freeagent_list_corporation_tax_returns",
    title: "FreeAgent List Corporation Tax Returns",
    description: "List corporation tax returns.",
    inputSchema: ListCorporationTaxReturnsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listCorporationTaxReturns,
  },
  {
    name: "freeagent_get_corporation_tax_return",
    title: "FreeAgent Get Corporation Tax Return",
    description: "Get a corporation tax return.",
    inputSchema: GetCorporationTaxReturnInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCorporationTaxReturn,
  },
  {
    name: "freeagent_transition_corporation_tax_return",
    title: "FreeAgent Transition Corporation Tax Return",
    description: "Mark corporation tax return filed/unfiled/paid/unpaid.",
    inputSchema: TransitionCorporationTaxReturnInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionCorporationTaxReturn,
  },
  {
    name: "freeagent_list_final_accounts_reports",
    title: "FreeAgent List Final Accounts Reports",
    description: "List final accounts reports.",
    inputSchema: ListFinalAccountsReportsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listFinalAccountsReports,
  },
  {
    name: "freeagent_get_final_accounts_report",
    title: "FreeAgent Get Final Accounts Report",
    description: "Get a final accounts report.",
    inputSchema: GetFinalAccountsReportInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getFinalAccountsReport,
  },
  {
    name: "freeagent_transition_final_accounts_report",
    title: "FreeAgent Transition Final Accounts Report",
    description: "Mark a final accounts report filed/unfiled.",
    inputSchema: TransitionFinalAccountsReportInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionFinalAccountsReport,
  },
  {
    name: "freeagent_list_income_tax_returns",
    title: "FreeAgent List Income Tax Returns",
    description: "List self assessment / income tax returns for a user.",
    inputSchema: ListIncomeTaxReturnsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listIncomeTaxReturns,
  },
  {
    name: "freeagent_get_income_tax_return",
    title: "FreeAgent Get Income Tax Return",
    description: "Get an income tax return.",
    inputSchema: GetIncomeTaxReturnInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getIncomeTaxReturn,
  },
  {
    name: "freeagent_transition_income_tax_return",
    title: "FreeAgent Transition Income Tax Return",
    description: "Mark an income tax return filed/unfiled.",
    inputSchema: TransitionIncomeTaxReturnInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionIncomeTaxReturn,
  },
  {
    name: "freeagent_transition_income_tax_return_payment",
    title: "FreeAgent Transition Income Tax Return Payment",
    description: "Mark an income tax payment paid/unpaid.",
    inputSchema: TransitionIncomeTaxReturnPaymentInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionIncomeTaxReturnPayment,
  },
  {
    name: "freeagent_list_payroll_periods",
    title: "FreeAgent List Payroll Periods",
    description: "List payroll periods for a tax year.",
    inputSchema: ListPayrollPeriodsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listPayrollPeriods,
  },
  {
    name: "freeagent_list_payroll_payslips",
    title: "FreeAgent List Payroll Payslips",
    description: "List payslips for a payroll period.",
    inputSchema: ListPayrollPayslipsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listPayrollPayslips,
  },
  {
    name: "freeagent_transition_payroll_payment",
    title: "FreeAgent Transition Payroll Payment",
    description: "Mark a payroll payment paid/unpaid.",
    inputSchema: TransitionPayrollPaymentInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: transitionPayrollPayment,
  },
  {
    name: "freeagent_list_payroll_profiles",
    title: "FreeAgent List Payroll Profiles",
    description: "List payroll profiles for a tax year.",
    inputSchema: ListPayrollProfilesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listPayrollProfiles,
  },
  {
    name: "freeagent_get_payroll_profile",
    title: "FreeAgent Get Payroll Profile",
    description: "Get payroll profile details.",
    inputSchema: GetPayrollProfileInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getPayrollProfile,
  },
  {
    name: "freeagent_list_properties",
    title: "FreeAgent List Properties",
    description: "List properties (UK unincorporated landlord).",
    inputSchema: ListPropertiesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listProperties,
  },
  {
    name: "freeagent_get_property",
    title: "FreeAgent Get Property",
    description: "Get a property.",
    inputSchema: GetPropertyInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getProperty,
  },
  {
    name: "freeagent_create_property",
    title: "FreeAgent Create Property",
    description: "Create a property.",
    inputSchema: CreatePropertyInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createProperty,
  },
  {
    name: "freeagent_update_property",
    title: "FreeAgent Update Property",
    description: "Update a property.",
    inputSchema: UpdatePropertyInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateProperty,
  },
  {
    name: "freeagent_delete_property",
    title: "FreeAgent Delete Property",
    description: "Delete a property.",
    inputSchema: DeletePropertyInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteProperty,
  },
  {
    name: "freeagent_list_stock_items",
    title: "FreeAgent List Stock Items",
    description: "List stock items (read-only FreeAgent API).",
    inputSchema: ListStockItemsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listStockItems,
  },
  {
    name: "freeagent_get_stock_item",
    title: "FreeAgent Get Stock Item",
    description: "Get a stock item.",
    inputSchema: GetStockItemInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getStockItem,
  },
  {
    name: "freeagent_list_hire_purchases",
    title: "FreeAgent List Hire Purchases",
    description: "List hire purchases (UK).",
    inputSchema: ListHirePurchasesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listHirePurchases,
  },
  {
    name: "freeagent_get_hire_purchase",
    title: "FreeAgent Get Hire Purchase",
    description: "Get a hire purchase.",
    inputSchema: GetHirePurchaseInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getHirePurchase,
  },
  {
    name: "freeagent_list_bank_feeds",
    title: "FreeAgent List Bank Feeds",
    description: "List bank feeds.",
    inputSchema: ListBankFeedsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listBankFeeds,
  },
  {
    name: "freeagent_get_bank_feed",
    title: "FreeAgent Get Bank Feed",
    description: "Get a bank feed.",
    inputSchema: GetBankFeedInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getBankFeed,
  },
  {
    name: "freeagent_list_email_addresses",
    title: "FreeAgent List Email Addresses",
    description: "List verified sender email addresses.",
    inputSchema: ListEmailAddressesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listEmailAddresses,
  },
  {
    name: "freeagent_list_account_locks",
    title: "FreeAgent List Account Locks",
    description: "List account locks.",
    inputSchema: ListAccountLocksInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listAccountLocks,
  },
  {
    name: "freeagent_set_account_lock",
    title: "FreeAgent Set Account Lock",
    description: "Set the user account lock date.",
    inputSchema: SetAccountLockInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: setAccountLock,
  },
  {
    name: "freeagent_delete_account_lock",
    title: "FreeAgent Delete Account Lock",
    description: "Clear the user account lock.",
    inputSchema: DeleteAccountLockInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteAccountLock,
  },
  {
    name: "freeagent_list_cis_bands",
    title: "FreeAgent List CIS Bands",
    description: "List CIS bands (UK CIS subcontractors).",
    inputSchema: ListCisBandsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listCisBands,
  },
  {
    name: "freeagent_get_cis_settings",
    title: "FreeAgent Get CIS Settings",
    description: "Get CIS settings.",
    inputSchema: GetCisSettingsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCisSettings,
  },
  {
    name: "freeagent_update_cis_settings",
    title: "FreeAgent Update CIS Settings",
    description: "Update CIS settings.",
    inputSchema: UpdateCisSettingsInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateCisSettings,
  },
  {
    name: "freeagent_list_sales_tax_periods",
    title: "FreeAgent List Sales Tax Periods",
    description: "List sales tax periods (US/Universal).",
    inputSchema: ListSalesTaxPeriodsInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: listSalesTaxPeriods,
  },
  {
    name: "freeagent_get_sales_tax_period",
    title: "FreeAgent Get Sales Tax Period",
    description: "Get a sales tax period.",
    inputSchema: GetSalesTaxPeriodInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getSalesTaxPeriod,
  },
  {
    name: "freeagent_create_sales_tax_period",
    title: "FreeAgent Create Sales Tax Period",
    description: "Create a sales tax period.",
    inputSchema: CreateSalesTaxPeriodInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createSalesTaxPeriod,
  },
  {
    name: "freeagent_update_sales_tax_period",
    title: "FreeAgent Update Sales Tax Period",
    description: "Update a sales tax period.",
    inputSchema: UpdateSalesTaxPeriodInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateSalesTaxPeriod,
  },
  {
    name: "freeagent_delete_sales_tax_period",
    title: "FreeAgent Delete Sales Tax Period",
    description: "Delete a sales tax period.",
    inputSchema: DeleteSalesTaxPeriodInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteSalesTaxPeriod,
  },
  {
    name: "freeagent_get_company_business_categories",
    title: "FreeAgent Get Company Business Categories",
    description: "List FreeAgent business categories.",
    inputSchema: GetCompanyBusinessTypesInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCompanyBusinessCategories,
  },
  {
    name: "freeagent_get_company_tax_timeline",
    title: "FreeAgent Get Company Tax Timeline",
    description: "Get upcoming tax timeline events.",
    inputSchema: GetCompanyTaxTimelineInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getCompanyTaxTimeline,
  },
  {
    name: "freeagent_get_user",
    title: "FreeAgent Get User",
    description: "Get a user by ID or me.",
    inputSchema: GetUserInputSchema.shape,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: getUser,
  },
  {
    name: "freeagent_create_user",
    title: "FreeAgent Create User",
    description: "Create a user.",
    inputSchema: CreateUserInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    handler: createUser,
  },
  {
    name: "freeagent_update_user",
    title: "FreeAgent Update User",
    description: "Update a user.",
    inputSchema: UpdateUserInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    handler: updateUser,
  },
  {
    name: "freeagent_delete_user",
    title: "FreeAgent Delete User",
    description: "Delete a user.",
    inputSchema: DeleteUserInputSchema.shape,
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
    handler: deleteUser,
  },
];
